name: dependecies
description: "dependecies"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  # ~~ =>3.6.0 <(3+1).0.0
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  #
  http:
    path: ./http-1.4.0
  #
  animations: ^2.0.11
  #
  geolocator: ^12.0.0

# only applied to the package as standalone app
# ignored when the package is used as a dependency
dependency_overrides:
  animations: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

