name: dependencies_exercise
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.1

# Add regular dependencies here.

#  pub.dev dependency
#  <unique name from pub.dev>
#    <version>

#  git dependency
#  <name the dependency is resolved with>
#    git
#      <url.git>
#      <ref> # commit hash/branch/...
#      <path> # path relative to the git repo's root (if package isn't at the root)

#  if the package is a part of sdk
#  sdk dependency resolves successfully if
#   - resolution is run with '<sdk name> pub ...'
#   - <sdk name> contains the dependency
#  <name>
#    sdk: <sdk name>

# version constraints
# - >, >=, <, <= <version>
# - x.y.z (exact version)
# ^x.y.z ~~ >=x.y.z <(x+1).y.z
# any

# dev dependencies of dependencies are ignored
# dependency imported from /test only -> it's a dev dependency
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
